### ISSUE TITLE
Hidden content negotiation?

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/purl.obolibrary.org#109]
This is odd. Not sure if it's an issue with purl.obolibrary.org or if I'm at fault

This fails:
```
owltools http://purl.obolibrary.org/obo/pato.obo
```

because it seems to be returning HTML:
```
Parser: OBOFormatOWLAPIParser
LINENO: 1 - Could not find tag separator ':' in line.
LINE: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
```

If I use the URL directly it succeeds:

```
owltools  https://raw.githubusercontent.com/pato-ontology/pato/master/pato.obo
```

This also succeeds:

```
wget --no-check-certificate http://purl.obolibrary.org/obo/pato.obo -o pato.obo
owltools pato.obo
```

I can't reproduce on `robot` as the `-I` doesn't appear to be working for any of the commands.

It could be possible owltools is doing some strange magic.. but AFAIK it's just issues a straight up call to the OWLAPI.

Perhaps the owlapi issues some odd user-agent metadata that causes the redirect server or github to work differently... will test this later.

**Comment by jamesaoverton** [comment]
`curl` and `wget` are returning OBO format for me, not HTML.

I don't have `owtools` installed at the moment. I can confirm that the ROBOT `-I` options aren't working.

**Comment by cmungall** [comment]
It seems this only happens when the following are all met

 * there is a redirect
 * the redirect is to https
 * the format is obo

**Comment by cmungall** [comment]
@jamesaoverton - yes curl and wget also return obo for me, so this works:

```
wget --no-check-certificate http://purl.obolibrary.org/obo/pato.obo -o pato.obo
owltools pato.obo
```

**Comment by cmungall** [comment]
It seems this has always been a problem, as this fails also:

```
owltools http://purl.oclc.org/obo/pato.obo
```

I was sure this uses to work...

So this is almost certainly the wrong tracker for me to be reporting this issue

**Comment by jamesaoverton** [comment]
I quickly hacked at ROBOT to test this, and it seemed to load `pato.obo` correctly. So I'm not sure that it's an OWLAPI thing.

    @Test
    public void testLoadOntologyFromURL() throws IOException, OWLOntologyCreationException {
        IRI iri = IRI.create("http://purl.obolibrary.org/obo/pato.obo");
        OWLOntologyManager manager = OWLManager.createOWLOntologyManager();
        OWLOntology ontology = manager.loadOntologyFromOntologyDocument(iri);
        System.out.println("LOAD URL");
        System.out.println(ontology);
    }

Output:

    LOAD URL
    Ontology(OntologyID(OntologyIRI(<http://purl.obolibrary.org/obo/pato.obo>))) [Axioms: 14578 Logical Axioms: 2327]
