### ISSUE TITLE
Protect master branch

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#112]
I would prefer to have all changes to code and configuration made via pull requests. Doing so ensures that Travis CI runs the automated test suite on every change before it lands on the `master` branch.

This is important because the new PURL server pulls from the `master` branch. Although it's designed to only pull when Travis is "green", enforcing this policy would add another layer of protection.

GitHub has some features that prevent branches from being deleted and require status checks:

https://help.github.com/articles/defining-the-mergeability-of-pull-requests/

I'm going to try enabling protection for `master` now. If that causes problems, we'll disable protections and try something else.

**Comment by jamesaoverton** [comment]
Ok. When editing a config file on GitHub (our recommended workflow) the commit-to-master option that was the default is now blocked: "You can’t commit directly to this branch because it is protected." You are forced to use "Create a new branch for this commit and start a pull request", which is what I wanted. This applies to everyone: admins and users.

**Comment by cmungall** [comment]
I approve!
