### ISSUE TITLE
Default redirect purl.obolibrary.org/obo/<namespace>[/] to configurable page

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/purl.obolibrary.org#137]
By default the recorded home page.

**Comment by jamesaoverton** [comment]
These cases are both supported, but require two different bits of syntax:

1. an `exact: /` entry will redirect a URL ending with a slash, like <http://purl.obolibrary.org/obo/obi/>
2. the `base_redirect: http://foo` field will redirect a URL without a final slash, like <http://purl.obolibrary.org/obo/obi>
