### ISSUE TITLE
PURLs for DINTO: Drug-drug Interaction Ontology

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#14]
http://purl.obolibrary.org/obo/dinto.owl points to a GitHub page, not an OWL file.

Currently BBOP redirects DINTO terms to Ontobee, but Ontobee does not include this ontology.

**Comment by jamesaoverton** [comment]
@beckyjackson hit this ancient issue with the Dashboard today. DINTO doesn't have a PURL config here, so it's falling through to OCLC and getting redirected to the GitHub HTML page for their repo, not an OWL file.

@cmungall @rvita Do you know the status of DINTO? It's marked as active in the OBO registry but now I have my doubts.

**Comment by cmungall** [comment]
See https://github.com/OBOFoundry/OBOFoundry.github.io/issues/208 and https://github.com/labda/DINTO/issues/1

**Comment by nlharris** [comment]
Sounds like it might be obsolete?

**Comment by jamesaoverton** [comment]
Marked obsolete in https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1202
