### ISSUE TITLE
FLOPO does not seem to build correctly

### ISSUE THREAD

**Issue by leechuck** [OBOFoundry/purl.obolibrary.org#181]
The flopo.owl product is not generated from its source; https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/flopo.md seems ok to me and points to the correct URL for the source file. I would appreciate any help in tracking down the problem, is there a log file somewhere in which I can check what part of the build process fails?

**Comment by jamesaoverton** [comment]
Hi @leechuck. This is the repository for PURL configuration -- we keep that separate from the ontology metadata, in https://github.com/OBOFoundry/OBOFoundry.github.io

Is the problem a missing PURL? If so, we need a pull request to create a `config/flopo.yml` file in this repository.

**Comment by leechuck** [comment]
Hi @jamesaoverton. Thank you, I created the file and did the pull request. I assume the "products" part of the yml file should point to berkeleybop and will be generated from the source of the flopo.md file at the main site automatically somehow? If there is a document describing the required workflow and the configuration parameters, please let me know.

Thank you for your help,
Rob.

**Comment by jamesaoverton** [comment]
Hi @leechuck. We haven't heard from @cmungall about this. Do you have an arrangement with BBOP to build FLOPO? They do build and host some ontologies, but not by default. Most of my projects build and host their own files, the PURLs just point to those files, and the registry in this repository just stores data about the projects.

**Comment by cmungall** [comment]
offline right now.

Welcome to use the central OBO berkeley build (no arrangement necessary, 
adding the build tag is sufficient), but you probably don't need to. See 
the 'what is the build tag' in the FAQ

**Comment by leechuck** [comment]
Thank you, this helps a lot. I now created a pull request for the PURL config file at https://github.com/OBOFoundry/purl.obolibrary.org/pull/182
