### ISSUE TITLE
Evaluate travis as a way to vet PRs

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/purl.obolibrary.org#2]
Assuming we could write some kind of validator for the htaccess files, it should be easy to write a .travis.yml that can be used to assist with PR evaluation.

**Comment by jamesaoverton** [comment]
Minimally, Travis could install a minimal Apache2 and run `apachectl configtest`: https://httpd.apache.org/docs/2.4/programs/apachectl.html

**Comment by jamesaoverton** [comment]
The current code uses Ansible and targets Debian 8 (Jessie). This works well for Vagrant and deployment. But Travis uses shell commands and Ubuntu 12.04: http://docs.travis-ci.com/user/installing-dependencies/

Switching from Debian to Ubuntu is not a big deal.

This guy uses Ansible inside Travis, but that strikes me as a bad idea: https://servercheck.in/blog/testing-ansible-roles-travis-ci-github

**Comment by jamesaoverton** [comment]
I want to pull from `master` directly to production, run `make`, and assume that everything will work. That could be contingent on a green light from Travis? Their API exposes `last_build_status`: http://docs.travis-ci.com/api/?http#repositories

If we can't do that, we'll have to do some sort of automatic rollback...

**Comment by jamesaoverton** [comment]
After a monstrous amount of trial and error, I think this is working correctly.
