### ISSUE TITLE
http://purl.obolibrary.org/obo/chmo/ doesn't resolve

### ISSUE THREAD

**Issue by rsc-ontologies** [OBOFoundry/purl.obolibrary.org#215]
Hello,

I'm pretty sure I updated the relevant .yml file (is it this one? https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/_config.yml) but I think something needs to be kicked behind the scenes. The OBO and OWL files are:
https://github.com/rsc-ontologies/rsc-cmo/blob/master/chmo.obo
and
https://github.com/rsc-ontologies/rsc-cmo/blob/master/chmo.owl

Best wishes,
Colin.

**Comment by rsc-ontologies** [comment]
Hello there,

Is there anything I can do myself to fix this?

Colin.

**Comment by cmungall** [comment]
This one:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/chmo.yml

The URLs are not correct - they need to resolve to the raw files, not HTML

**Comment by simonjupp** [comment]
e.g. https://raw.githubusercontent.com/rsc-ontologies/rsc-cmo/master/chmo.owl

While you are at it can you update mop and rxno as they have same issue?

**Comment by cmungall** [comment]
http://purl.obolibrary.org/obo/chmo.owl resolves now
