### ISSUE TITLE
http://purl.obolibrary.org/obo/pato# does not redirect 

### ISSUE THREAD

**Issue by mobb** [OBOFoundry/purl.obolibrary.org#236]
Hello - 
We are importing pato into another ontology, along with several other OBO ontologies. The other imports' namespaces resolve to http://www.berkeleybop.org/. the PATO namespace points to a 404 (https://github.com/pato-phenotype/pato#). We do see a dir http://www.berkeleybop.org/ontologies/pato/ -- perhaps pato is supposed to redirect there, too?
thanks.

**Comment by cmungall** [comment]
These are the PURLs you should use for the ontology

http://purl.obolibrary.org/obo/pato.obo
http://purl.obolibrary.org/obo/pato.owl

Don't hardcode any berkeleybop URLs, always use the PURLs

We should have it such that http://purl.obolibrary.org/obo/pato 
redirects to the homepage. Just curious is this a technical issue for 
you?

**Comment by mobb** [comment]
Hi Chris -
We're having problems with Protege importing a file that uses the 
namespace: http://purl.obolibrary.org/obo/pato#

It's in this 
file:https://github.com/DataONEorg/sem-prov-ontologies/blob/master/observation/d1-ECSO.owl
(top reproduced below)

and also in one of it's imports: 
https://github.com/DataONEorg/sem-prov-ontologies/blob/master/observation/PATO_import.owl

Are you saying that the namespace for pato should not follow the pattern 
we used for uo and envo?

thanks -
Margaret


<?xml version="1.0"?>
<rdf:RDF xmlns="http://purl.dataone.org/odo/ECSO_/"
      xml:base="http://purl.dataone.org/odo/ECSO_/"
      xmlns:owl="http://www.w3.org/2002/07/owl#"
      xmlns:oboInOwl="http://www.geneontology.org/formats/oboInOwl#"
      xmlns:ns="http://creativecommons.org/ns#"
      xmlns:xsd="http://www.w3.org/2001/XMLSchema#"
      xmlns:skos="http://www.w3.org/2004/02/skos/core#"
      xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#"
      xmlns:envo="http://purl.obolibrary.org/obo/envo#"
xmlns:skosdl="http://www.w3.org/TR/skos-reference/skos-owl1-dl#"
      xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
      xmlns:ecso="http://purl.dataone.org/odo/ECSO_"
      xmlns:xml="http://www.w3.org/XML/1998/namespace"
xmlns:oboe-core="http://ecoinformatics.org/oboe/oboe.1.2/oboe-core.owl#"
      xmlns:pato="http://purl.obolibrary.org/obo/pato#"
      xmlns:uo="http://purl.obolibrary.org/obo/uo#"
      xmlns:odo="http://purl.dataone.org/odo/"
      xmlns:obo="http://purl.obolibrary.org/obo/"
xmlns:oboe-characteristics="http://ecoinformatics.org/oboe/oboe.1.2/oboe-characteristics.owl#"
      xmlns:dc="http://purl.org/dc/elements/1.1/">
     <owl:Ontology rdf:about="http://purl.dataone.org/odo/ECSO_">
         <owl:imports 
rdf:resource="http://purl.dataone.org/obo/UO_import.owl"/>
         <owl:imports 
rdf:resource="http://purl.dataone.org/PATO_import.owl"/>
         <owl:imports 
rdf:resource="http://ecoinformatics.org/oboe/oboe.1.2/oboe.owl"/>
         <owl:imports 
rdf:resource="http://purl.dataone.org/obo/ENVO_import.owl"/>
         <owl:imports 
rdf:resource="http://www.w3.org/TR/skos-reference/skos-owl1-dl.rdf"/>


-----------
Margaret O'Brien
Information Management
Marine Science Institute, UCSB
Santa Barbara, CA 93106
805-893-2071 (voice)
http://sbc.lternet.edu

**Comment by cmungall** [comment]
I don't know exactly what you mean by:
> We're having problems with Protege importing a file that uses the namespace: http://purl.obolibrary.org/obo/pato#

note that namespace declarations are local to each document. As far as any software is concerned, everything is expanded to a full URI.

I'm not really following what you are trying to do with your imports. It looks as if you have extracted modules from ontologies like PATO, UO. However, they don't appear to resolve:

```
$ curl http://purl.dataone.org/PATO_import.owl
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://purl.dataone.org/PATO_import.owl">here</a>.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at purl.dataone.org Port 80</address>
</body></html>
```

This is nothing to do with PATO though.

> Are you saying that the namespace for pato should not follow the pattern we used for uo and envo? 

I don't follow. PATO, UO and all the OBO Library ontologies should behave in the same way. You can either import the complete ontology using the official OBO purl. Or you can use your favorite module extraction tools (ROBOT, OntoFox, etc) to create a submodule which you would give a purl that you take charge of resolving. But this has nothing to do with namespaces.

You can also email obo-discuss for further help (about to leave to a meeting...)

**Comment by mobb** [comment]
Sorry - too many examples. I have removed them from the git comment. 
This is the problem:

You say:
> We should have it such that 
> http://purl.obolibrary.org/obo/patoredirects to the homepage. Just 
> curious is this a technical issue for you?
http://purl.obolibrary.org/obo/pato does not redirect.

-----------
Margaret O'Brien
Information Management
Marine Science Institute, UCSB
Santa Barbara, CA 93106
805-893-2071 (voice)
http://sbc.lternet.edu

**Comment by cmungall** [comment]
OK, we will have this resolve to the home page. Is this in line with 
your expectations?

**Comment by mobb** [comment]
yes.

-----------
Margaret O'Brien
Information Management
Marine Science Institute, UCSB
Santa Barbara, CA 93106
805-893-2071 (voice)
http://sbc.lternet.edu

**Comment by saralafia** [comment]
The PATO namespace
http://purl.obolibrary.org/obo/pato#
redirects to 
https://github.com/pato-phenotype/pato#
which is broken. Is it supposed to point to
http://www.berkeleybop.org/ontologies/pato/
? Thanks!

**Comment by cmungall** [comment]
There should be no hashes in any PATO PURL. Where did you come across this URL?
