### ISSUE TITLE
Use new URL for central berkeley/obo fileserver

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/purl.obolibrary.org#261]
Globally replace

http://berkeleybop.org/ontologies/

with

http://ontologies.berkeleybop.org/

(which is serving files from S3/CF rather than NFS off a server in berkeley)

Don't do this until this job finishes https://build.berkeleybop.org/job/simple-build-obo-all/1670/

And test with a few ontologies first, e.g. uberon

cc @kltm

**Comment by kltm** [comment]
From: https://build.berkeleybop.org/job/simple-build-obo-all/1670/console
```
FAIL: trans # THIS SHOULD NOT FAIL
FAIL: agro # THIS SHOULD NOT FAIL
FAIL: symp # THIS SHOULD NOT FAIL
```
But this may be fine, yes?
All said there seem to be just under 20 ontologies that got uploaded. That seems rather small compared to the number available on the current server.

**Comment by kltm** [comment]
I'd note the uberon seems to have not made it.

**Comment by cmungall** [comment]
Turns out if it redballs it doesn't run the s3cmd step, which is totally reasonable.

Doing what I should have done a while ago: if any `infallible` ontologies do fail, mark the build as unstable (yellow) rather than hard failure.

Additional context for others viewing this PR: http://obofoundry.org/faq/what-is-the-build-field.html -- this explains the  `infallible` tag i the build object

**Comment by cmungall** [comment]
Keeping this open until we globally redirect berkeleybop.org/ontologies to ontologies.berkeleybop.org

**Comment by cmungall** [comment]
this was done a while ago
