### ISSUE TITLE
ddanat.owl does not resolve

### ISSUE THREAD

**Issue by balhoff** [OBOFoundry/purl.obolibrary.org#266]
At http://ontologies.berkeleybop.org/ddanat.owl (from http://purl.obolibrary.org/obo/ddanat.owl):

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>ddanat.owl</Key>
<RequestId>BE95A01CEAC18FD6</RequestId>
<HostId>peGNQHgNqyzmMNTUl/mRL83amg5ff6NkW1OCKc76oqhsq7dq6ZwLWocSteg8wY4OgoMJavJyJaA=</HostId>
</Error>
```

**Comment by cmungall** [comment]
I'll try and look at this later. Ddamat uses the central build it doesn't
make its own releases.

**Comment by cmungall** [comment]
Broader issue: https://github.com/OBOFoundry/OBOFoundry.github.io/issues/257#issuecomment-264208775

**Comment by cmungall** [comment]
resolved
