### ISSUE TITLE
Add purls for OHD

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/purl.obolibrary.org#272]
OHD has been around for some time but was never registered. As it is already in Ontobee and has been in circulation, and since it predates our policies for registration, I propose it be added directly rather than going through an after-the-fact request to obo-discuss.

A pull request has been made

**Comment by jamesaoverton** [comment]
Fixed by a2ac552ed0b84b68c6655b8a95beae09fb983899
