### ISSUE TITLE
http://purl.obolibrary.org/obo/so.owl 404 error

### ISSUE THREAD

**Issue by tgbugs** [OBOFoundry/purl.obolibrary.org#274]
http://purl.obolibrary.org/obo/so.owl is no longer resolving because https://raw.githubusercontent.com/The-Sequence-Ontology/SO-Ontologies/master/so-xp.owl no longer exists due to renaming. Cross referencing https://github.com/The-Sequence-Ontology/SO-Ontologies/issues/383.

**Comment by jamesaoverton** [comment]
Thanks for the heads up! It's fixed now.
