### ISSUE TITLE
Geno purl exists but not in the config folder

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/purl.obolibrary.org#283]
https://github.com/OBOFoundry/Operations-Committee/issues/160

I thought @mbrush would need a PURL but it turns out the PURL already exists and resolves, http://purl.obolibrary.org/obo/geno.owl, though there is no entry under https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config

@cmungall, @jamesaoverton: any idea?

**Comment by jamesaoverton** [comment]
There should be a configuration file here. I'll merge it.

In order to avoid breaking things, if a PURL is not found here it will redirect to the old system or the Berkeley server. We need to revisit that policy.
