### ISSUE TITLE
geno.yml fails test missing term_browser:

### ISSUE THREAD

**Issue by alanruttenberg** [OBOFoundry/purl.obolibrary.org#287]
term_browser: is required  - should it be optional?

**Comment by jamesaoverton** [comment]
Two things:

1. term_browser defaults to ontobee, so we could make it optional. In general I prefer to be explicit. For term_browser specifically, I like having an example term ID to test.

2. Despite not having term_browser, geno.yml passed the Travis tests, so I merged it: https://travis-ci.org/OBOFoundry/purl.obolibrary.org/builds/190343322

A missing term_browser probably won't do any harm, but I'm very unhappy to see Travis passing something that should fail the schema checks.
