### ISSUE TITLE
issue with versionIRI and PURLs

### ISSUE THREAD

**Issue by mcourtot** [OBOFoundry/purl.obolibrary.org#296]
I created a tagged release on GH as per the ontology-starter-kit directions, which has version IRI  http://purl.obolibrary.org/obo/duo/releases/2017-01-31/duo.owl

The GH tag is at https://github.com/EBISPOT/DUO/tree/v2017-01-31

The PURL configuration is at https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/duo.yml, and contains
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/EBISPOT/DUO/releases/v

However, the version IRI doesn't resolve. Any idea where I went wrong?

**Comment by jamesaoverton** [comment]
I think I fixed it, but please check. The server should update in the next 20 minutes.

**Comment by mcourtot** [comment]
Thanks @jamesaoverton, that worked.
