### ISSUE TITLE
updated geo.yml for PURLs -- adding PURL for new file

### ISSUE THREAD

**Issue by hoganwr** [OBOFoundry/purl.obolibrary.org#322]
see fork commit 033934d222f526a9c336d89f9052b81d6f2a5f69

**Comment by jamesaoverton** [comment]
Looks fine. Can you make this a pull request?

**Comment by hoganwr** [comment]
I really hate being a dunce, but I've been trying to figure out how to make it a pull request.  When I compare master with 033934d, the create pull request button disappears, and yet it shows me the changes to geo.yml...

**Comment by jamesaoverton** [comment]
I'm also confused about that. I'll look into it.
