### ISSUE TITLE
NCIT OBO term resolution

### ISSUE THREAD

**Issue by balhoff** [OBOFoundry/purl.obolibrary.org#349]
The Ontobee group have now loaded the OBO Edition of NCIT which we're working on. However term IRIs are not redirecting properly. I don't think I understand how it is supposed to work. Based on what I see in configs for other ontologies I added an `/about/` section to the config:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/0d9b231ba769ca2cf4b4bb7e978c8a092dac79f7/config/ncit.yml#L19-L20

This matches term pages at Ontobee such as http://www.ontobee.org/ontology/NCIT?iri=http://purl.obolibrary.org/obo/NCIT_C92628

However the term IRI first redirects to oclc.org (and then to berkeleybop.org):

```
$ curl http://purl.obolibrary.org/obo/NCIT_C92628
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://purl.oclc.org/obo/NCIT_C92628">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at purl.obolibrary.org Port 80</address>
</body></html>
```

Confusingly, CTENO uses the same type of `/about/` entry, but the redirect does not go where it is stated (`www.ontobee.org/browser` vs. `www.ontobee.org/ontology`):

```
$ curl http://purl.obolibrary.org/obo/CTENO_0000001
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>303 See Other</title>
</head><body>
<h1>See Other</h1>
<p>The answer to your request is located <a href="http://www.ontobee.org/browser/rdf.php?o=CTENO&amp;iri=http://purl.obolibrary.org/obo/CTENO_0000001">here</a>.</p>
<hr>
<address>Apache/2.4.18 (Ubuntu) Server at purl.obolibrary.org Port 80</address>
</body></html>
```

**Comment by cmungall** [comment]
This line:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/9853193f7cf54e79678e0831bfe4188e4ca86c39/tools/translate-terms.py#L49

makes an assumption about PURLS, that the local ID is all numeric. 

We make an assumption for PRO, but it looks like they have an entirely different base redirect

**Comment by jamesaoverton** [comment]
The Apache config file for IDSPACE "FOO" is located in `/obo/foo/.htaccess`. That file can only configure paths that start with `/obo/foo/`. This prevents one project from breaking another's config. To configure `/obo/FOO_*` we need to change the `/obo/.htaccess` file, shared with all the projects. The Python file Chris pointed to builds this configuration for projects that use Ontobee.

Yes, it assumes that term IDs are numeric. When that assumption fails, we can build custom rules in `obo.yml`, like this: https://github.com/OBOFoundry/purl.obolibrary.org/blob/9853193f7cf54e79678e0831bfe4188e4ca86c39/config/obo.yml#L63

**Comment by balhoff** [comment]
Thanks, I made a pull request for obo.yml in case you think that's the right way to go.

**Comment by jamesaoverton** [comment]
Yes. The `ncit.yml` should also say `term_browser: custom`.

I'm away from my desk this afternoon. If you need it done fast, maybe Chris can check and merge.

James
