### ISSUE TITLE
HAO term IRIs do not resolve

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#368]
Example: <http://purl.obolibrary.org/obo/HAO_0000908> redirects to <http://ontologies.berkeleybop.org> which just gives an S3 XML file. It should probably redirect to <http://api.hymao.org/api/ontology/ontology_class/HAO_0000908>.

The problem seems to be that `hao.yml` sets `term_browser: custom` but there is no custom term browser defined for it in `obo.yml`.

**Comment by jamesaoverton** [comment]
@balhoff or anybody from HAO: Am I right that the term IRIs should redirect to <http://api.hymao.org/api/ontology/ontology_class/>? If so, I can fix this quickly.

**Comment by balhoff** [comment]
Yes that's right. It used to work?

**Comment by jamesaoverton** [comment]
Thanks @balhoff. Yes, it used to work...

@cmungall what was the reason for removing HAO term redirects? https://github.com/OBOFoundry/purl.obolibrary.org/commit/0113c825572392aa88221ea78437b78a0998330d#diff-1510e906d40e28bb6f6d96f98e8bbce5

**Comment by mjy** [comment]
Thanks all for the super speedy response, let me know if I need to do any config on `hao.yml`.

**Comment by balhoff** [comment]
@jamesaoverton we had come to the conclusion that this was supposed to do the job:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/fb9efe32805997490b0d22794bf6fd99db1622b0/config/hao.yml#L23-L24

Is that incorrect? Or is the central file the only way for an ontology to point to an alternative term page?

**Comment by jamesaoverton** [comment]
@balhoff: Sorry, I don't know what you mean by "alternative term page". Maybe I'm missing something.

The bug report from @mjy that I saw on the Ontobee mailing list was about <http://purl.obolibrary.org/obo/HAO_0000908> redirecting to something weird. There's no problem with <http://purl.obolibrary.org/obo/hao/about/HAO_0000908>.

The underlying Apache `.htaccess` files are hierarchical (by `/`), so the only way to redirect <http://purl.obolibrary.org/obo/HAO_*> is with an entry in `obo.yml`. The entry that @cmungall deleted was redirecting to <http://api.hymao.org/api/ontology/ontology_class/HAO_*>, which is my understanding of the correct behaviour in this case. The `hao.yml` file can only redirect <http://purl.obolibrary.org/obo/hao/**>.

**Comment by cmungall** [comment]
Sorry I thought this was some relic, and assumed we were doing redirects purely within each group's individual yml file rather than the global one, revert my change if you need to

**Comment by balhoff** [comment]
@jamesaoverton I just mean specifying a non-OntoBee place for term IRI redirect.

**Comment by balhoff** [comment]
Can the central redirection generally route `http://purl.obolibrary.org/obo/$ONT_*` to `http://purl.obolibrary.org/obo/$obo/about/*` to distribute control of this? Sorry if I haven't fully thought this through. :-)

**Comment by jamesaoverton** [comment]
@balhoff: I considered that during the initial design and decided against it. Unfortunately I can't find any documentation on that decision or my thought process.

There's only a handful of ontologies that have custom term browsers. I'm going to revert 0113c82 and close this. If you want to talk more about `/about/` then please open a new issue.

Thanks everyone!

**Comment by mjy** [comment]
All. thanks very much for the super speedy response.  Just in time for the talk being given. Tested and working, consider closed from my side of things.
