### ISSUE TITLE
Certain PRO purls not resolving

### ISSUE THREAD

**Issue by nataled** [OBOFoundry/purl.obolibrary.org#383]
Some PRO terms have identifiers that are UniProt-ish; that is, use the UniProtKB accession. These include terms for specific protein isoforms, which in UniProtKB are indicated by <accession><dash><integer>. An example from PRO, with full URL:

http://purl.obolibrary.org/obo/PR_P20263-1

This fails to go to the intended page:

research.bioinformatics.udel.edu/pro/entry/PR_P20263-1

Instead a generic berkeleybop XML is returned. It's unclear what the issue is, as this used to work just fine, and all other (non-dash-containing) PURLs still work fine. So far as I know, no changes were made on our end to cause this.

**Comment by jamesaoverton** [comment]
We've got a custom regular expression for PRO IDs: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obo.yml#L65

It doesn't handle the dashes. We can either add another special case or simplify it to match more stuff. Should we relax it to match any string of non-whitespace characters? `^/obo/PR_(\S+)$`

**Comment by nataled** [comment]
That would be going too far, I think. What's odd is that this was an issue three and a half years ago, but was fixed (according to Chris Mungall) to allow an optional dash followed by an optional one-or-more integer(s). Somehow that fix has gone away. I cannot find an example of the regex used back then, but I believe it should be something like:

regex: ^/obo/PR_(\d+|[OPQ][0-9][A-Z0-9]{3}[0-9]|[A-NR-Z][0-9]([A-Z][A-Z0-9]{2}[0-9]){1,2}\-*\d*)$

though what I wrote above isn't quite right because the final \d part is required ONLY if there is a dash. Note too that the dash is only allowed for the version of PRO IDs that is not all digit (so, it applies only to the part after the pipe). Also, ignore my statement about the intended page going to udel and keep it where it goes currently (georgetown).

**Comment by nataled** [comment]
(Note: it appears that the escape I entered in front of the dash has disappeared upon entering my comment, as has the asterisk after both the dash and the d)

**Comment by jamesaoverton** [comment]
The current regex has three patterns, separated by pipes. In #384 I modified the second pattern to allow for `PR_P20263-1`. Are there IDs like `PR_Q9BWV1-1` from the third group?

**Comment by nataled** [comment]
Ah, sorry, I missed the other pipe. So the first group is for identifiers like PR_000001234 (which never gets dashes), the second group is for identifiers like the one we've been discussing (with six-character strings starting with O, P, or Q, optionally followed by a dash and digit(s), the third is for cases like other six- or 10 character strings, such as PR_A0A0E0NEP8. These too can be followed by the dash and digit(s).

**Comment by jamesaoverton** [comment]
Ok I updated #384 to allow for `PR_A0A0E0NEP8-1`. How many digits are allowed after the dash?

**Comment by nataled** [comment]
I've never seen more than two, though there is no hard restriction there. I'd say it would be safe to restrict to two, as the highest number I've observed is currently 37.

**Comment by jamesaoverton** [comment]
Ok. I'll allow one-or-more digits. (Which is what you said above -- I should have read a bit more carefully.)
