### ISSUE TITLE
NCBITaxon base url

### ISSUE THREAD

**Issue by Public-Health-Bioinformatics** [OBOFoundry/purl.obolibrary.org#418]
In purl.obolibrary.org/config/ncbitaxon.yml it appears that the base url is set with lowercase:

    # PURL configuration for http://purl.obolibrary.org/obo/ncbitaxon

    idspace: NCBITaxon
    base_url: /obo/ncbitaxon

But terms are listed as e.g. http://purl.obolibrary.org/obo/NCBITaxon_9031 
So shouldn't the base_url be "/obo/NCBITaxon" ?

The OLS people were having a minor error show up as a result of this discrepancy - their API search couldn't detect which terms were local to NCBI and which were imported.
Thx,
Damion

**Comment by cmungall** [comment]
not sure I follow. Most use uppercase for the ID, but the bases are all lowercase. Not sure why NCBITaxon is any different. @simonjupp ?

**Comment by Public-Health-Bioinformatics** [comment]
Ah, it looks like error was at OLS configuration end, not in purl.obolibrary.org/config/ncbitaxon.yml 
Thanks for replying. They've resolved it at OLS.
