### ISSUE TITLE
problem with automatic checks?

### ISSUE THREAD

**Issue by ramonawalls** [OBOFoundry/purl.obolibrary.org#449]
I created a pull request for an updated yaml file about an hour ago. Usually the checks run right away, but nothing has happened this time.

https://github.com/OBOFoundry/purl.obolibrary.org/pull/448

**Comment by jamesaoverton** [comment]
The tests actually passed on Travis, but for some reason GitHub is not reading them as passed. That's a problem on their end.

Your PR was fine so I merged it and made sure the changes are live. Let me know if you have any more trouble.

**Comment by ramonawalls** [comment]
Thanks @jamesaoverton!
