### ISSUE TITLE
Decide on editing workflow(s)

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#5]
I think that the Apache server should run directly against the master branch. So master can only contain vetted changes with updated `.htaccess` files that have passed the automatic tests (#2, #3).

From the user's perspective, easiest to hardest:

1. create a new issue with your request; an admin will make a pull request, test it automatically, then merge the PR
2. use GitHub to edit the `config/foo.yml` file in your browser; that should automatically make a pull request? somebody still has to update the `.htaccess` file
3. fork the repo, edit `config/foo.yml`, run a Python script, commit to the fork, and make a pull request with updated YAML and .htaccess files

**Comment by kltm** [comment]
1 is nice, and fits in with an automated travis checking system--check the schema, then run the test server and test all of the URLs; if passes accept request onto master; the addition to master triggers the rollout to a production site.

2 can just be a special case of 1: fork, edit in browser, PR. It would be super easy to setup a video guide for it.

In my mind, ideally, the .htaccess files wouldn't ever be committed to the repo--they are just temporary downstream product (although they would be available for debugging and inspection in Jenkins and Travis). In the same way you wouldn't commit a .fasl or .o file, the apache-specific product would be merely a specifc target product. Moreover, the more you commit to the repo, the more churn there is and the harder commit messages are to read.

**Comment by jamesaoverton** [comment]
I agree in general that you should not commit generated files. I'm a little nervous about these particular generated files, but automated tests should build confidence in them.

For option 3, I've just added commit dcf0313d0836444b8fdc7c8214653a783404c062 with code for a local VM with Vagrant and Ansible. One advantage is that it should work cross-platform.

**Comment by jamesaoverton** [comment]
In commit dd5836e082e3eaaa1914d88d4fcaafcd9fa71850 I removed the generated files. There are now examples in `tools/examples/` instead.

But to do this right, we need a bulletproof solution for #2, so the master branch is never broken.

**Comment by jamesaoverton** [comment]
I added instructions in 3297f50d89fb86f7c94ebe00c1a172ee418e6113. These can be changed or improved, but they'll do for now.
