### ISSUE TITLE
ontology iri (http://purl.obolibrary.org/obo/labo.owl) is redirecting to non-existent files

### ISSUE THREAD

**Issue by bluesman** [OBOFoundry/purl.obolibrary.org#575]
looks like some ontology repos may have been moved recently causing a redirect error:

e.g. http://purl.obolibrary.org/obo/labo.owl redirects to: 

https://raw.githubusercontent.com/OpenLHS/LABO/master/Releases/2019-08-29/LABO.owl

which no longer exists.

this is preventing me from building the ontology-development-kit (https://github.com/INCATools/ontology-development-kit) as it uses robot to convert these 

i think it may have been this commit:
https://github.com/OpenLHS/LABO/commit/e030326c8b8122908829fb68779f0b97b03a1137

seems like the redirect should be updated (rather than that commit being reverted) but i defer

**Comment by bluesman** [comment]
same for: http://purl.obolibrary.org/obo/pdro.owl

**Comment by jamesaoverton** [comment]
Thanks @bluesman.

@pfabry: I see that you followed my advice in #568 to use the GitHub release mechanism for LABO with this commit: https://github.com/OpenLHS/LABO/commit/e030326c8b8122908829fb68779f0b97b03a1137 Please update the [`labo.yml`](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/labo.yml) PURL configuration to use the new release URLs.

I've created PR #576 for PDRO.

**Comment by jamesaoverton** [comment]
Thanks again @bluesman. @pfabry has updated these configs.
