### ISSUE TITLE
Create a PURL for OBO-Central artefacts

### ISSUE THREAD

**Issue by cmungall** [OBOFoundry/purl.obolibrary.org#601]
We often hardcode URLs like this:

 * https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/registry/ontologies.yml
 * https://raw.githubusercontent.com/OBOFoundry/OBOFoundry.github.io/master/registry/obo_context.jsonld
 * https://raw.githubusercontent.com/iconic/open-iconic/master/svg/

e.g. in the OBO dashboard code.

I propose we have a PURL space http://purl.obolibrary.org/registry/ for these

If we agree on the base URL then I can go ahead and try and make changes

**Comment by jamesaoverton** [comment]
I think this was addressed in #427 and #428, but we just haven't been using those PURLs consistently.

**Comment by cmungall** [comment]
Had a feeling I was repeating myself!
