### ISSUE TITLE
Term redirects for PR

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#68]
@alanruttenberg

Unlike other ontologies, PR has a bunch of "PRO_" entries on PURL.org. [Here's the first 100 in XML](https://purl.org/admin/purl/?target=&seealso=&maintainers=&explicitmaintainers=&tombstone=false&p_id=/obo/PRO_*). There's probably more than these 100, but I don't know how to see find them with this search system.

These first 100 don't do anything special.

Are these term redirect rules sufficient to cover those entries? https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obo.yml#L39

**Comment by cmungall** [comment]
I vote for abandoning them

**Comment by alanruttenberg** [comment]
Remove the PRO_ entries, they are obsolete and remnants of an earlier version.  Also remove the below as the namespace for the protein ontology is PR, not PRO 

- regex: ^/obo/PRO_(\d+)$
  replacement: http://pir.georgetown.edu/cgi-bin/pro/entry_pro?id=PRO_$1
  tests:
  - from: /PRO_000000001
    to: http://pir.georgetown.edu/cgi-bin/pro/entry_pro?id=PRO_000000001

**Comment by jamesaoverton** [comment]
Thanks @alanruttenberg. I removed the PRO_ term redirect rule from `obi.yml` in this branch:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/fix-pro/config/obo.yml

What about this `pro.yml` config file that I created to handle `/obo/pro/about/`? Delete it?

https://github.com/OBOFoundry/purl.obolibrary.org/blob/fix-pro/config/pro.yml

**Comment by jamesaoverton** [comment]
I'll remove `pro.yml` for now. We can reinstate it later.

**Comment by jamesaoverton** [comment]
Closed by commit 36c5fa6b790c0c73b29f6437a4ae7d9cffecfa10.
