### ISSUE TITLE
PURLs for NCRO

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#69]
I don't see a release OWL file yet. Should http://purl.obolibrary.org/obo/ncro.owl redirect to
https://github.com/OmniSearch/ncRO-Ontology-Files/raw/master/ncro-owl-WorkingVersion-06302015.owl

@alanruttenberg ?

**Comment by alanruttenberg** [comment]
I wasnt sure about the main purl yet.  I only defined ncro/dev/ncro.owl in the .md

I'll check and take care of it once the new purl system is in place.

**Comment by cmungall** [comment]
I'd recommend against putting version numbers in the filename. Version 
control systems such as Git should take care of this for you

**Comment by alanruttenberg** [comment]
Yes, of course. I've reorganized their repo and have instructed them about
this.

**Comment by jamesaoverton** [comment]
Fixed by commit f8a220aecd432b71ee948440dab85b88163012f4
