### ISSUE TITLE
request for specific PURL for the OMP issue tracker

### ISSUE THREAD

**Issue by dsiegele** [OBOFoundry/purl.obolibrary.org#70]
We would like to request a PURL:  http://purl.obolibrary.org/obo/omp/devel/omp-term-request
that directs to:   https://github.com/microbialphenotypes/OMP-ontology/issues.

The reason for our request is that this PURL is listed in the published paper that describes the OMP project.  When we migrated the project repository to github, the short PURL that was made initially (/obo/omp/devel/) no longer worked--it directs to 'Page Not Found'. We would like the long PURL listed in the paper to continue working and so are requesting this new PURL.

The longer discussion that led up to this request is on the obofoundry issue tracker:
https://github.com/OBOFoundry/OBOFoundry.github.io/issues/132

**Comment by jamesaoverton** [comment]
This test URL <http://url.ontodev.org/obo/omp/devel/omp-term-request> now points to your issue tracker <https://github.com/microbialphenotypes/OMP-ontology/issues>.

The PURL you requested will be active once the new system is deployed, which is planned for Monday.
