### ISSUE TITLE
How can I determine which release I am getting from purl?

### ISSUE THREAD

**Issue by antonkratz** [OBOFoundry/purl.obolibrary.org#704]
Using python and the import library, I am downloading the GO from Purl like this:
`r = requests.get('http://purl.obolibrary.org/obo/go/go-basic.obo')`
How can I determine which release that is? I.e. I want to know which release is in the current http://purl.obolibrary.org/obo/go/go-basic.obo

**Comment by jamesaoverton** [comment]
The second line of that file says "data-version: releases/2020-10-09". Are you asking for something else?

**Comment by matentzn** [comment]
Its probably not what you are asking, but if you _knew_ the version, you could retrieve the ontology like this:

http://purl.obolibrary.org/obo/go/releases/2020-10-09/go-basic.obo
