### ISSUE TITLE
Update PURL for MOD ontology

### ISSUE THREAD

**Issue by pmt706** [OBOFoundry/purl.obolibrary.org#710]
Hi I'm the new ontology coordinator for the MOD ontology.  The current PURL points to an old version.  The correct version can be found here:  https://raw.githubusercontent.com/HUPO-PSI/psi-mod-CV/master/PSI-MOD.obo  We don't have an updated .owl version... is that able to be generated automatically?  Sorry for the questions... kinda new at this!

**Comment by jamesaoverton** [comment]
Sure, happy to answer your questions. The best way to convert `.obo` to `.owl` is ROBOT's `convert` command. Please take a look:

http://robot.obolibrary.org/convert

**Comment by pmt706** [comment]
Thanks.  After correcting a mistake in my obo file this worked flawlessly.  Let me get my obo changes merged then I'll get the owl added to our repository and I'll come back here to update the ticket and get our entry updated.

**Comment by pmt706** [comment]
Hi there.  We've got a proper owl now too: https://raw.githubusercontent.com/HUPO-PSI/psi-mod-CV/master/PSI-MOD.owl

Are we now able to update our PURL?  Thanks.

**Comment by jamesaoverton** [comment]
The .owl and .obo files look good to me at a quick glance.

Please follow the README to update https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/mod.yml and make a PR. If you need help, just let me know.

**Comment by pmt706** [comment]
Thanks done with #712
