### ISSUE TITLE
KISAO has a md file, but no purl config

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/purl.obolibrary.org#787]
https://github.com/OBOFoundry/OBOFoundry.github.io/blob/master/ontology/kisao.md

See also https://github.com/EBISPOT/OLS/issues/498

@matthiaskoenig can you supply a kisao.yml file, along the lines of these:
https://github.com/OBOFoundry/purl.obolibrary.org/tree/master/config

Thank you!

**Comment by matthiaskoenig** [comment]
@matentzn See pull request https://github.com/OBOFoundry/purl.obolibrary.org/pull/792
