### ISSUE TITLE
New PURL config for DISDRIV

### ISSUE THREAD

**Issue by lschriml** [OBOFoundry/purl.obolibrary.org#799]
I have created disdriv.yml, following the approval of this namespace at the last obo foundry operations meeting. 
The metadata file has been vetted and approved. 
Thank you,
Lynn Schriml

**Comment by jamesaoverton** [comment]
@beckyjackson Could you draft a PURL config for this project, please?

**Comment by beckyjackson** [comment]
It looks like this file already exists - https://raw.githubusercontent.com/OBOFoundry/purl.obolibrary.org/master/config/disdriv.yml

The redirect works for http://purl.obolibrary.org/obo/disdriv.owl

**Comment by beckyjackson** [comment]
Sorry, the redirect isn't quite right. I'll fix that.

**Comment by lschriml** [comment]
Are there additional steps for the new PURL and the creation of an obofoiundry page ?

**Comment by jamesaoverton** [comment]
I think this is all complete, so I'll close both issues.

**Comment by lschriml** [comment]
Thank you James. 
I was looking on the obo foundry site and disdriv is not yet there. 
How do those pages get populated? 

Much appreciated,
Lynn

**Comment by jamesaoverton** [comment]
Yes, there's just one more step to update obofoundry.org: https://github.com/OBOFoundry/OBOFoundry.github.io/pull/1652
