### ISSUE TITLE
New purl for EPIO

### ISSUE THREAD

**Issue by phwegner** [OBOFoundry/purl.obolibrary.org#812]
Currently, we have http://purl.obolibrary.org/obo/epso.owl assigned as PURL. And this one works correctly but for our paper, it would be great if we could also have the purl : http://purl.obolibrary.org/obo/epio.owl. 

All configs are in the epio.yml in the repository.

**Comment by matentzn** [comment]
Seems like we deployed a faulty config:

https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/epio.yml#L5


You should make a PR to change this to epio.owl.

**Comment by phwegner** [comment]
@matentzn I created a pull request. Thank you for noticing that !

**Comment by jamesaoverton** [comment]
#813 fixes a bug, so now <http://purl.obolibrary.org/obo/epio.owl> works and <http://purl.obolibrary.org/obo/epso.owl> no longer works. To my understanding, this is the correct behaviour.

What is the argument for claiming both PURLs?
