### ISSUE TITLE
Migrate out final domains in OBO Google domains

### ISSUE THREAD

**Issue by kltm** [OBOFoundry/purl.obolibrary.org#819]
Following on from https://github.com/OBOFoundry/purl.obolibrary.org/issues/771 and discussing with @jamesaoverton , we'll migrate out the following domains to LBL AWS:

- [ ] obofoundry.com
- [ ] obofoundry.net
- [ ] obi-ontology.org

These would follow the same pattern as before: 1) setup records, 2) migrate, 3) test (if there were records).

The end state is that there are no longer any "OBO" registrations left in Google Domains (one down).

Tagging @cmungall @abessiari

**Comment by abessiari** [comment]
@jamesaoverton 
@kltm 

FYI: The transfer  is complete.

a) obofoundry.com. did not have any records.

b) obofoundry.org had two records. 
    - www.obofoundry.net. (CNAME)
    - obofoundry.net (MX) 
c) obi-ontology.org
   - obi-ontology.org (A)

**Comment by kltm** [comment]
Looks good! (assuming that b's obofoundry.org is a typo)

**Comment by abessiari** [comment]
yes it is. I have corrected it.
