### ISSUE TITLE
Update SBO yaml config file

### ISSUE THREAD

**Issue by rsmsheriff** [OBOFoundry/purl.obolibrary.org#861]
Can you please update the SBO.yml config file below
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/sbo.yml

Replace 
- sbo.owl: http://www.ebi.ac.uk/sbo/exports/Main/SBO_OWL.owl
with 
- sbo.owl: https://raw.githubusercontent.com/EBI-BioModels/SBO/master/SBO_OWL.owl

and remove 
- sbo.obo: http://www.ebi.ac.uk/sbo/exports/Main/SBO_OBO.obo
as we are not generating .obo file now.

**Comment by jamesaoverton** [comment]
Yes, we can certainly update the `sbo.owl` PURL as requested.

PURLs are intended to be permanent, so it would be best not to remove the `sbo.obo` PURL. Would it be possible to create an updated `sbo.obo` with [`robot convert`](http://robot.obolibrary.org/convert)? If not, could you provide a link to an older version of `sbo.obo`?

**Comment by ntung** [comment]
Hi @jamesaoverton ,

Thank you for your response. I reply to you on behalf of our team who used to develop and maintain the SBO service. 

As you suggested, I have converted the `owl` file to `obo` one and pushed it to [[could](https://raw.githubusercontent.com/EBI-BioModels/SBO/master/SBO_OBO.obo)](https://raw.githubusercontent.com/EBI-BioModels/SBO/master/SBO_OBO.obo). Could you please update the relevant URL of `sbo.obo` to the GitHub URL:
`https://raw.githubusercontent.com/EBI-BioModels/SBO/master/SBO_OBO.obo`.

Best,
Tung
