### ISSUE TITLE
Update rule for non-numeric PR IDs

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#88]
As soon as the new system went live, I could see GoogleBot crawling PR IDs such as PR_Q9BWV1. The current rule for PR in [`obo.yml`](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/obo.yml)  only matches numeric IDs, so these are failing over to the old system. (Not a problem in the short-term.)

What do you suggest @alanruttenberg ?

**Comment by jamesaoverton** [comment]
These IDs are accounting for a large fraction of the traffic, so I'd like to handle them properly, soon.

**Comment by jamesaoverton** [comment]
They are currently redirecting like this #89 to proper 200 pages (based on spot checking).

**Comment by alanruttenberg** [comment]
The non-numeric ids should be handled on a case by case basis. The only ontology that I know of that does this is PRO, which has representations of protein classes that refer to the same thing as uniprot entries point to.

This page: http://www.uniprot.org/help/accession_numbers gives a regex for UniprotKB identifiers which can be adapted for PRO. If you see other than PRO non-numeric ids, I think you should file an issue and we can have a look.
