### ISSUE TITLE
Half of all hits since deploying are from one IP for ARG_2000379

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#90]
Anybody know what "ARC Reader (http://arc.semsol.org/)" is? Apparently the term is ["contact"](https://code.google.com/p/connect-isf/source/browse/trunk/src/ontology/source/contact.owl?spec=svn239&r=239).

Fully 50% of all my access logs so far are pairs of lines like this:

```
23.253.170.101 - - [23/Nov/2015:16:33:08 +0000] "GET /obo/ARG_2000379 HTTP/1.0" 302 304 "-" "ARC Reader (http://arc.semsol.org/)" "http://purl.oclc.org/obo/ARG_2000379"
23.253.170.101 - - [23/Nov/2015:16:33:08 +0000] "GET /obo/ARG/about/ARG_2000379 HTTP/1.0" 302 314 "-" "ARC Reader (http://arc.semsol.org/)" "http://purl.oclc.org/obo/ARG/about/ARG_2000379"
```

They come in pairs because of ugly term bouncing: #89.

**Comment by jamesaoverton** [comment]
The request eventually bounces to a 404 on PURL.org. Sometimes I get several of these requests per second. The domain http://arc.semsol.org resolves to a "for sale" page.

**Comment by jamesaoverton** [comment]
The new system isn't even breaking a sweat (touch wood), so this isn't a big problem, but it's bugging me.

**Comment by jamesaoverton** [comment]
I'm tempted to write a special rule just to 404 this ID.

**Comment by jamesaoverton** [comment]
The ARG PURL.org entries were created by @carlotorniai, @mellybelly, and @ShahimEssaid. Any thoughts, guys?

ARG isn't in the ID registry...

**Comment by jamesaoverton** [comment]
@mbrush also created some PURL.org entries for ARG. Any thoughts about this?

**Comment by cmungall** [comment]
https://www.w3.org/2001/sw/wiki/ARC

https://github.com/semsol/arc2/

cc @semsol

**Comment by bnowack** [comment]
I've updated ARC Reader's user agent URL so that the library can be found again (might make things easier for others in similar situations...).

**Comment by jamesaoverton** [comment]
Thanks @bnowack. Any idea who could be running that machine at 23.253.170.101? It seems to be on [Rackspace](http://rackspace.com) cloud hosting.

I'm still seeing 50% of all requests from that one IP, for that one term ID.

**Comment by bnowack** [comment]
No idea, I'm afraid...
ARC2 used to be popular in SemWeb circles a few years ago. Could well be some forgotten RDF crawler still doing its thing (not sure why they let it hit remote servers so frequently, though).

**Comment by jamesaoverton** [comment]
@bnowack: Ok, thanks for your help!

**Comment by bnowack** [comment]
I sent out a [tweet](https://twitter.com/bengee/status/669182397007699969), with a bit of luck it'll make it to the right person...

**Comment by ShahimEssaid** [comment]
I'll forward this issue to the VIVO folks to see if they know the server.

**Comment by jamesaoverton** [comment]
Despite @bnowack and @ShahimEssaid's help, nobody has stepped forward about this rogue server in a week. Shahim suggests blocking the IP and seeing if anyone notices a problem. I'm tempted, but not sure.

If we decide to block the IP, we can tweak [our Apache config](https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/tools/etc_apache2_sites-available_site.j2) following this [Access Control How To](https://httpd.apache.org/docs/2.4/howto/access.html):

    <RequireAll>
        Require all granted
        Require not ip 23.253.170.101
    </RequireAll>

**Comment by ShahimEssaid** [comment]
If the logging is the main issue, one option is to exclude the log entries
for this IP and other noisy logging. This article has some details:
https://www.howtoforge.com/setenvif_apache2

Does the PURL service send any caching headers by default? Some caching
configuration might reduce the hits if the client or intermediate hosts
recognize this.

**Comment by jamesaoverton** [comment]
I'm not really worried about the logs. I haven't configured any caching headers. This rogue server is unlikely to respect them, but I suppose an intermediary might.

This rogue server isn't a problem by itself, just an annoyance. But it's a reason to think more deeply about how to handle abuse of the service.

**Comment by cmungall** [comment]
@jamesaoverton is this still a problem?

**Comment by jamesaoverton** [comment]
I haven't looked at the logs in a long time. This was not a really problem, just an annoyance. I'll close.
