### ISSUE TITLE
Mmusdv not resolving 

### ISSUE THREAD

**Issue by shawntanzk** [OBOFoundry/purl.obolibrary.org#903]
currently purls for MmusDv aren't resolving (eg http://purl.obolibrary.org/obo/MmusDv_0000062)
On investigation, OntoBee does not seem to have MmusDv in it and the config uses term_browser: ontobee
OLS does however have MmusDv in it (eg https://www.ebi.ac.uk/ols/ontologies/mmusdv/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMmusDv_0000062) 
Was wondering if we could change the redirect to OLS or make sure MmsuDv is in OntoBee 
Not 100% sure who the owner is of that but I see @jamesaoverton & @cmungall having edited the config file

Thanks

**Comment by jamesaoverton** [comment]
I think the PURL server is working correctly, so I'm going to close this with some suggested next steps.

Ontobee may have a problem, in which case you can ask for support on their mailing list: <https://groups.google.com/g/ontobee-discuss>. The MmusDv project owners can choose to switch to OLS by making a PR in this repository. You could raise that as an issue on their tracker <https://github.com/obophenotype/developmental-stage-ontologies/issues>.
