### ISSUE TITLE
Switch all `term_browser: ols` PURLs to OLS4

### ISSUE THREAD

**Issue by matentzn** [OBOFoundry/purl.obolibrary.org#920]
Background:

1. OLS3 (https://www.ebi.ac.uk/ols/index) is no longer maintained and will be switched off on the 30th October
2. OLS URLs like `https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0098743` will be forwarded to OLS4 (`https://www.ebi.ac.uk/ols4/ontologies/go/classes?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0098743`) on the 30th October
3. A lot of new terms are no longer resolving to OLS (because they are not updated in OLS3)
4. The PURL resolve to pages that show outdated content

I would like to propose to switch the OLS redirect to OLS4 obo-wide now, instead of waiting until end of October, to avoid the churn coming with the additional communication of "why does this IRI not resolve" etc.

**Comment by jamesaoverton** [comment]
Good explanation!

My proposal is update the PURL generation code here to point to OLS4: https://github.com/OBOFoundry/purl.obolibrary.org/blob/2689416a5bc7a1e82d7196243eeff0b6587a0dff/tools/translate_yaml.py#L311

So all ontology projects that set `term_browser: ols` in their PURL config will switch to OLS4 with that change. (Then we can clean up some specific configs.)
