### ISSUE TITLE
update cmo.yml

### ISSUE THREAD

**Issue by tutajm** [OBOFoundry/purl.obolibrary.org#930]
The current source for obo and owl files points to files that are very old -- from year 2019.

The new source will point to files that are updated weekly (if needed)

- cmo.owl: https://download.rgd.mcw.edu/ontology/clinical_measurement/clinical_measurement.owl
- cmo.obo: https://download.rgd.mcw.edu/ontology/clinical_measurement/clinical_measurement.obo

**Comment by jamesaoverton** [comment]
Closed by #931
