### ISSUE TITLE
Configure release PURLs for VT

### ISSUE THREAD

**Issue by jamesaoverton** [OBOFoundry/purl.obolibrary.org#972]
@zhilianghu The PURLs for the VT ontology are configured here: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/vt.yml

If you want "release" PURLs with the pattern `http://purl.obolibrary.org/obo/vt/releases/*` then you need an entry like this:

```yaml
- prefix: /releases/
  replacement: https://raw.githubusercontent.com/AnimalGenome/vertebrate-trait-ontology/v
```

If you can make a Pull Request with that change, that would be great. If not let me know and I'll help.

**Comment by zhilianghu** [comment]
Thanks James for the prompt reply but your suggested URL is incomplete or truncated that I cannot see how it works.

I wish to point out that it is not “I” want to go one way or the other; it is that “how” can I make changes on my github site in order for the current YML to work?
https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/vt.yml

Zhiliang

From: "James A. Overton" ***@***.***>
Reply-To: "OBOFoundry/purl.obolibrary.org" ***@***.***>
Date: Wed, Jan 31, 2024 at 04:14 PM
To: "OBOFoundry/purl.obolibrary.org" ***@***.***>
Cc: Zhiliang Hu ***@***.***>, Mention ***@***.***>
Subject: [OBOFoundry/purl.obolibrary.org] Configure release PURLs for VT (Issue #972)


@zhilianghu<https://github.com/zhilianghu> The PURLs for the VT ontology are configured here: https://github.com/OBOFoundry/purl.obolibrary.org/blob/master/config/vt.yml

If you want "release" PURLs with the pattern http://purl.obolibrary.org/obo/vt/releases/* then you need an entry like this:

- prefix: /releases/

  replacement: https://raw.githubusercontent.com/AnimalGenome/vertebrate-trait-ontology/v

If you can make a Pull Request with that change, that would be great. If not let me know and I'll help.

**Comment by jamesaoverton** [comment]
@zhilianghu I think this PR is what you want, please let me know: https://github.com/OBOFoundry/purl.obolibrary.org/pull/973

If the purpose is not clear, please read the first parts of the README for this repository. If it's still not clear, let me know and I'll try to explain better.

**Comment by zhilianghu** [comment]
It does seem to be the way we follow.  I made comments following the #973.

Thanks for bridging this topic over!

From: "James A. Overton" ***@***.***>
Reply-To: "OBOFoundry/purl.obolibrary.org" ***@***.***>
Date: Thu, Feb 01, 2024 at 02:23 PM
To: "OBOFoundry/purl.obolibrary.org" ***@***.***>
Cc: Zhiliang Hu ***@***.***>, Mention ***@***.***>
Subject: Re: [OBOFoundry/purl.obolibrary.org] Configure release PURLs for VT (Issue #972)


@zhilianghu<https://github.com/zhilianghu> I think this PR is what you want, please let me know: #973<https://github.com/OBOFoundry/purl.obolibrary.org/pull/973>

If the purpose is not clear, please read the first parts of the README for this repository. If it's still not clear, let me know and I'll try to explain better.

**Comment by jamesaoverton** [comment]
I think this has been addressed.
