### ISSUE TITLE
CDNO github URL change not reflected in config/cdno.yml

### ISSUE THREAD

**Issue by NutrientInstitute** [OBOFoundry/purl.obolibrary.org#992]
CDNO changed github URLs from https://github.com/Southern-Cross-Plant-Science/cdno to https://github.com/CompositionalDietaryNutritionOntology/cdno, after the ontology was made a project separate from Southern Cross University. 

I will create a pull request to reflect this change.

**Comment by jamesaoverton** [comment]
Closed by #993
